### ISSUE TITLE
Gestion du panier

### ISSUE THREAD

**Issue by raphpion** [raphpion/ift215_devoir4#3]

**Comment by leandeurrrr** [comment]
Dans l'ensemble c'est pas mal good pour le panier, le seul truc c'est que je ne peux pas gérer si on ajoute plus d'items qu'il n'y en a dans la réserve.

**Comment by raphpion** [comment]
Quand tu modifies la quantité dans le panier est ce que tu fais une requête pour changer la quantité en stock ? Si oui, techniquement la demande devrait échouer lorsque tu veux ajouter plus de produits qu'il y en a.

Regarde sur ma branche ce que j'ai fait pour l'inscription, d'afficher un message d'erreur en cas de demande échouée, tu pourrais implémenter la même chose sur la page panier !

Donc l'ordre serait :

1. Tenter de modifier la quantité de stock du produit
2. Tenter de modifier le panier de l'utilisateur
